services:
  postgres:
    image: postgres:15-alpine
    container_name: push_reminder_postgres
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: node:20-alpine
    container_name: push_reminder_migrations
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    command: >
      sh -c "npm install && npx prisma migrate deploy"
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: push_reminder_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    container_name: push_reminder_user
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.prod
    ports:
      - "3000:3000"

  notification:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
    container_name: push_reminder_notification
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env.prod
    ports:
      - "3001:3001"

volumes:
  postgres_data:
  redis_data:
